### ISSUE TITLE
Load modules from a config file or autodetect them

### ISSUE THREAD

**Issue by Otto-AA** [ActivityWatch/aw-qt#35]
As mentioned in [this todo](https://github.com/ActivityWatch/aw-qt/blob/09c57363b1f87df1454a550d6b7a2a564e343126/aw_qt/manager.py#L112) it would be helpful to dynamically load the list of modules which should be started.

The current workaround is to change the modules list in [manager.py](https://github.com/ActivityWatch/aw-qt/blob/09c57363b1f87df1454a550d6b7a2a564e343126/aw_qt/manager.py#L112) and the one in [main.py](https://github.com/ActivityWatch/aw-qt/blob/09c57363b1f87df1454a550d6b7a2a564e343126/aw_qt/main.py#L33)

**Comment by ErikBjare** [comment]
Actually, check out this PR: https://github.com/ActivityWatch/aw-qt/pull/27

**Comment by Otto-AA** [comment]
Oh, I didn't see that one. That's exactly what I've wished for ^_^

**Comment by ErikBjare** [comment]
Should be fixed now that https://github.com/ActivityWatch/aw-qt/pull/56 is merged.
