### ISSUE TITLE
I can't see the aw-qt binary file after having downloaded activitywatch on windows

### ISSUE THREAD

**Issue by ManishBhat** [ActivityWatch/aw-qt#46]
I am trying to run the file using Hyper, a pseudo-Linux terminal for windows.
![image](https://user-images.githubusercontent.com/9575623/58217476-f52e3a00-7cd0-11e9-82b5-47d1ea3d915a.png)
I can't find the binary file on my computer and apparently nor can Hyper.
I have attached images of the file directory as well.
![aw-qt2](https://user-images.githubusercontent.com/9575623/58217663-c6649380-7cd1-11e9-882d-c930d22e3b21.PNG)
![aw-qt3](https://user-images.githubusercontent.com/9575623/58217664-c6649380-7cd1-11e9-8d09-ded65fad5a0a.PNG)
![aw-qt4](https://user-images.githubusercontent.com/9575623/58217665-c6fd2a00-7cd1-11e9-96de-ca2ac2eb865b.PNG)

**Comment by ManishBhat** [comment]
I am sure I am making a rookie mistake. I would be really grateful for any help.

**Comment by johan-bjareholt** [comment]
Looks like you have downloaded the source code, not the pre-built application.

This is where you find the pre-built application: https://github.com/activitywatch/activitywatch/releases
