### ISSUE TITLE
Build fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by mherlev** [ActivityWatch/aw-qt#58]
Build fails on Ubuntu 20.04 with the error:
ERROR: Package 'aw-qt' requires a different Python: 3.8.2 not in '>=3.6,<3.8'

Seems to be caused by commit https://github.com/ActivityWatch/aw-qt/commit/91f250b8235efaa2fb53b75ba0570c2b5ab6336e

What was the reason for downgrading?

I've tried changing the .toml to include 3.8.2, but that results in:
ERROR: Could not find a version that satisfies the requirement sip<4.20,>=4.19.4 (from PyQt5==5.10.1->aw-qt==0.1.0) (from versions: 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.1.2, 5.2.0)
ERROR: No matching distribution found for sip<4.20,>=4.19.4 (from PyQt5==5.10.1->aw-qt==0.1.0)

**Comment by ErikBjare** [comment]
The reason is complicated and related to PyInstaller which doesn't play nice with newer versions of PyQt5 (and the older ones aren't available for Python 3.8). 

For now, you'll just have to use Python 3.7 or lower if you want to build, sorry about that.
