### ISSUE TITLE
"Open log folder" opens a web browser

### ISSUE THREAD

**Issue by kroq-gar78** [ActivityWatch/aw-qt#70]
Clicking on the "Open log folder" opens up a Chrome window with my log directory, rather than a file browser. This is particularly strange since Chrome isn't my default web browser. Running `xdg-open` manually with either of these commands gives the intended behavior (opening with file browser):

 * `xdg-open "file:///$HOME/.cache/activitywatch/log/"`
 * `xdg-open "$HOME/.cache/activitywatch/log/"`

Opening the dashboard and API browser work correctly and use my default browser.

I'm on Ubuntu 18.04 using the v0.10.0 ActivityWatch distributable.

**Comment by ErikBjare** [comment]
Hmm, this looks like a variation of a previous issue we had with opening the dashboard.

We probably need to modify this code:

https://github.com/ActivityWatch/aw-qt/blob/c7d1cd364b8f0308787e985f35312f3c77bdef1e/aw_qt/trayicon.py#L64-L71

To use the save workaround as this code:

https://github.com/ActivityWatch/aw-qt/blob/c7d1cd364b8f0308787e985f35312f3c77bdef1e/aw_qt/trayicon.py#L28-L51

**Comment by johan-bjareholt** [comment]
I did the workaround @ErikBjare mentioned, should fix the issue.

@kroq-gar78 Since I can't reproduce though, If this doesn't work in the next release please add a comment and I'll re-open this issue.
