### ISSUE TITLE
Separate the manager from the UI

### ISSUE THREAD

**Issue by jifalops** [ActivityWatch/aw-qt#84]
I'm using ChromeOS and to track its Linux activity I had to start each component manually and it's not really working. Events aren't being logged from the chrome extension even though the extension says it's connected to the server (might just be in testing mode). 

Anyway if the management part was separate it'd also make #32 easier.

**Comment by johan-bjareholt** [comment]
The UI is already seperate from the manager, aw-webui is completely independent of aw-qt.

I'd recommend opening up a new issue marked support instead with more details about what's not working for you.

**Comment by ErikBjare** [comment]
@johan-bjareholt I'm not sure, but I think they mean separating the tray icon from the underlying service/process manager.
